config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  # get '/articles', to: "articles#index"
  # get "/articles/:id", to: "articles#show"
  resources :articles do
    resources :comments
    member do
      delete 'delete_image'
      get :download_image
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  # has_one_attached :image, dependent: :destroy
  has_many_attached :images, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  validates :images, content_type: {in:[:png, :jpg, :jpeg], message: "is not png, jpg,or jpeg"},
  size: { between: 1.kilobyte..20.megabytes , message: 'must be less than 20MB in size' }

  def image_as_thumbnail
    return unless image.content_type.in?(%w[image/jpeg image/jpg image/png])
    image.variant(resize_to_limit: [800, 400]).processed
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy download_image delete_image]

  def index
    @articles = Article.all
  end

  def show
    # @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    # if @article.save
    #   redirect_to @article
    # else
    #   render :new, status: :unprocessable_entity
    # end
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    # @article = Article.find(params[:id])
  end

  def update
    # @article = Article.find(params[:id])

    # pp "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", params[:article][:image_ids]
    # if params[:article][:image_ids]
    #   params[:article][:image_ids].each do |image_id|
    #     image = @article.images.find(image_id)
    #     image.purge
    #   end
    #   params[:article].delete :image_ids
    # end

    # if @article.update(article_params)
    #   # flash[:success] = "編集しました"
    #   redirect_to @article
    # else
    #   render :edit, status: :unprocessable_entity
    # end
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def download_image
    # @article = Article.find(params[:id])
    image = @article.images.find(params[:image_id])
    file = image.blob.download

    if send_data(file, disposition: 'attachment',
                 filename: image.blob.filename.to_s,
                 type: image.blob.content_type)
      # head :no_content
    else
      render json: @article.errors, status: :not_found
    end
  end

  def delete_image
    # @article = Article.find(params[:id])
    image = @article.images.find(params[:image_id])
    image.purge

    # redirect_to edit_article_path(@article)
    respond_to do |format|
      format.html { redirect_to edit_article_path(@article), notice: "Image was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def destroy
    # @article = Article.find(params[:id])
    @article.destroy

    # redirect_to root_path, status: :see_other
    respond_to do |format|
      format.html { redirect_to root_path, status: :see_other, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :body, :status, images: [])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    # redirect_to article_path(@article)
    respond_to do |format|
      format.html { redirect_to article_path(@article) }
      format.json { head :no_content }
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    # redirect_to article_path(@article), status: :see_other
    respond_to do |format|
      format.html { redirect_to article_path(@article), status: :see_other, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:commenter, :body, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :images %><br>
    <%= form.file_field :images, multiple: true %><br>

    <%= form.label :title %><br>
    <%= form.text_field :title, size: 40 %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body, size: "60x3" %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || 'public' %>
  </div><br>

  <div>
    <%= form.submit nil, class: "btn btn-success" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<p style="color: green"><%= notice %></p>

<h1>Edit Article</h1>

<!-- <%= render "form", article: @article %> -->
<%= form_with model: @article do |form| %>

  <% @article.images.each do |image| %>
    <%= form.hidden_field :images, multiple: true, value: image.signed_id %>
  <% end %>

  <div>
    <%= form.label :images %><br>
    <%= form.file_field :images, multiple: true %><br>

    <%= form.label :title %><br>
    <%= form.text_field :title, size: 40 %>
    <% @article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body, size: "60x3" %><br>
    <% @article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: @article.status || 'public' %>
  </div><br>

  <div>
    <%= form.submit nil, class: "btn btn-success" %>
  </div>
<% end %>

<br><p><%= link_to "Cancel", @article, class:"btn btn-primary" %></p>

<% if @article.images.present? %>
  <p><% @article.images.each do |image| %>
    <%= image_tag image, width:300 %>
    <%= link_to  delete_image_article_path(@article, image_id: image.id),
        class:"btn btn-danger",
        data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } do %>
    <i class="fe fe-trash"></i>
    Destroy Image
    <% end %></p>
  <% end %>
<% end %>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<p>
  Our page has <%= Article.public_count %> articles and
  <%= Article.where(status: 'public').map {|i| i.images.count}.sum %> images.
</p>

<div class="container container-m">
<div class="card-deck">
<% @articles.order('updated_at DESC').each do |article| %>
  <% unless article.archived? %>
    <div class="col-sm-12 col-md-6 col-lg-4 ">
      <div class="card card-outline-dark text-center">
        <%= link_to article do %>
          <% if article.images.attached? %>
            <%= image_tag article.images.first.variant(resize: 600, gravity: "center", crop: "300x300+0+0") %>
          <% else %>
            <%= image_tag('person_noimage.jpg', width:300) %>
          <% end %>
        <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to article.title, article %></h5>
          <p class="card-text"><small class="text-muted"><%= article.images.count %> file(s)</small></p>
          <p class="card-text"><small class="text-muted">Updated at <%= article.updated_at %></small></p>
          <!-- <div class="card-footer text-body-secondary"><small class="text-muted"><%= article.updated_at %></small></div> -->
        </div>
      </div>
    </div>
  <% end %>
<% end %>
</div>
</div>

<!-- <p> -->
<!--   <%= link_to new_article_path, class:"btn btn-primary" do %> -->
<!--     <i class="fe fe-plus"></i> -->
<!--     New Article -->
<!--   <% end %> -->
<!-- </p> -->

app/views/articles/new.html.erb
<p style="color: green"><%= notice %></p>

<h1>New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= @article.title %></h1>

<% if @article.images.attached? %>
  <% @article.images.each do |image| %>
    <div class="container-image col-lg-6 col-md-9">
     <%= link_to url_for(image) do %>
       <%= image_tag image.variant(resize: 500) %>
     <% end %>
     <p style="padding-top: 1rem" >
     <%= link_to download_image_article_path(@article, image_id: image.id),
         title:"Download This Image",
         class:"btn btn-primary" do %>
           <i class="fe fe-download" style="font-size: 1.5rem; color: white;"></i>
           &nbsp;Download Image
           <% end %></p>
    </div>
    <div class="container-fluid" ></div>
   <% end %>
<% end %>

<p><%= @article.body %></p>

<!-- <p><%= link_to "Edit", edit_article_path(@article), class:"btn btn-primary" %> -->
<%= link_to edit_article_path(@article), class:"btn btn-primary" do %>
  <i class="fe fe-gear"></i>
  Edit
<% end %>

<%= link_to article_path(@article),
    class:"btn btn-danger",
    data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?" } do
    %>
  <i class="fe fe-trash"></i>
  Destroy Article
<% end %>

<h2>Comments</h2>
<%= render @article.comments %>

<div class="container-comment col-lg-6 col-md-9" >
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
</div>
<div class="container-fluid" ></div>

<!-- <p><%= link_to "Home", root_path, class:"btn btn-primary"  %></p> -->
<p><%= link_to root_path, class:"btn btn-primary" do %>
  <i class="fe fe-home"></i>
  Home
  <% end %>
</p>

<!-- <%= link_to root_path, class: "btn btn-primary" do %> -->
<!--   <i class="fe fe-heart" aria-hidden="true"></i> -->
<!--   Root -->
<!-- <% end %> -->

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to [comment.article, comment], class:"btn btn-danger",data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } do %>
      <i class="fe fe-trash"></i>
      Destroy Comment
    <% end %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter, size: 40 %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body, size: "60x3" %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: 'public' %>
  </p>
  <p>
    <%= form.submit nil, class: "btn btn-success" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photographer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-cloud">
      <div class="container-fluid navbar-cloud-elem">
        <%= link_to root_path, class:"btn blank", style:"margin-left:3rem" do %>
        <i class="fe fe-home"></i>
        HOME
        <% end %>

        <%= link_to new_article_path, class:"btn btn-primary", style:"float:right;margin-right:3rem" do %>
        <i class="fe fe-plus"></i>
        New Article
        <% end %>

        <button type="button" class="btn blank" style="float:right;margin-right:3rem">
          <%= ENV['USER'] %>@<%= ENV['RAILS_ENV'] %>
        </button>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>